FORMAT: 1A
HOST: https://iot-sprinkler.herokuapp.com/

# iot-sprinkler

Sprinkler API which waters gardens

## Sprinkler [/webapi/houses/{house_id}]

### Start Sprinkler [PUT /webapi/houses/{house_id}/task1?time={time}]

This is for Sprinkler Scheduler to notify sprinkler. Then sprinkler will check the sensors
and decide whether to start. If sprinkler is already on, time will be reset

`house_id`   ID of the house in which the sprinkler is placed

`time`  Period of time in seconds for which the sprinkler should be on. If not specified, 60 seconds will be set.

+ Parameters
    + house_id (string) - ID of the house in which the sprinkler is placed
    + time (number) - Period of time in seconds for which the sprinkler should be on. If not specified, 60 seconds will be set.
    

+ Response 200 (application/json)
    
        {
            "house_id": "1"
            "status": "on"
            "seconds_left": 60
        }

+ Response 403 (application/json)

        {
            "reason": "who cares, this damn thing doesn't work :D"
        }
        
### Stop Sprinkler [PUT /webapi/houses/{house_id}/task2]

Turns sprinkler off. If sprinkler is already off, nothing will happen.

`house_id`   ID of the house in which the sprinkler is placed.

+ Parameters
    + house_id (string) - ID of the house in which the sprinkler is placed
    
+ Response 200 (application/json)
    
        {
            "house_id": "1"
            "status": "off"
            "seconds_left": 0
        }

+ Response 403 (application/json)

        {
            "reason": "who cares, this damn thing doesn't work :D"
        }