FORMAT: 1A
HOST: https://iot-sprinkler.herokuapp.com/

# iot-sprinkler

Sprinkler API which waters gardens

## Sprinkler [/webapi/houses/{house_id}]

### Get Sprinkler Status [GET /webapi/houses/{house_id}/task]

Returns current status of the sprinkler.

`house_id`   ID of the house in which the sprinkler is placed

+ Parameters
    + house_id (string) - ID of the house in which the sprinkler is placed.

+ Response 200 (application/json)
    
        {
            "house_id": "1"
            "status": "on"
            "duration": 60
        }
        
+ Response 200 (application/json)
    
        {
            "house_id": "1"
            "status": "off"
        }

+ Response 403 (application/json)

        {
            "reason": "who cares, this damn thing doesn't work :D"
        }

### Change Sprinkler Status [PUT /webapi/houses/{house_id}/task]

Turns sprinkler on or off depending on the request body.

If duration is given in the request body, sprinkler will be on for the specified time, otherwise
default value of 60 seconds will be used.

`house_id`   ID of the house in which the sprinkler is placed


+ Parameters
    + house_id (string) - ID of the house in which the sprinkler is placed.
    

+ Request (application/json)

        {
            "house_id": "1"
            "set_status": "on",
            "duration": 50
        }
        
+ Request (application/json)

        {
            "house_id": "1"
            "set_status": "on"
        }
        
+ Request (application/json)

        {
            "house_id": "1"
            "set_status": "off"
        }

+ Response 200 (application/json)
    
        {
            "status": "on"
            "seconds_left": 50
        }    

+ Response 200 (application/json)
    
        {
            "status": "on"
            "seconds_left": 60
        }
        
+ Response 200 (application/json)
    
        {
            "status": "off"
        }

+ Response 403 (application/json)

        {
            "reason": "who cares, this damn thing doesn't work :D"
        }